defaults: &defaults
  driver: mysql
  host: localhost
  db: cp_db
  port: "3306"
  charset: "utf8mb4"

prod:
  user: root
  password: admin
  <<: *defaults

dev:
  user: root
  password: admin
  <<: *defaults